name: Run Postman Collection with Newman

on:
  push:
    branches:
      - main
    paths:
      - 'NewCollection.postman_collection.json' # Tu colección
      - '.github/workflows/api-tests.yml'        # El propio pipeline
  pull_request:
    branches:
      - main
    paths:
      - 'NewCollection.postman_collection.json'
      - '.github/workflows/api-tests.yml'
  workflow_dispatch: # Mantiene el botón manual por si acaso

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Versión más reciente

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Versión más reciente
        with:
          node-version: '18'

      - name: Install Newman and htmlextra
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Newman collection
        run: |
          newman run postman/collections/postman/collections/51642953-2d43d61d-09c4-40d3-9855-e4cf88b4dc10.json -r htmlextra --reporter-htmlextra-export newman-report.html || true

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
